# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2af45fcd500963416135afd9993cc835b009b5d2075bf3b9cf1fce416d1ba5476f5d7430359afbf545e02bcfe434c9ece154713c2dd6930945d1f6924ba008e

test:
  secret_key_base: 6f5bc82546fad38c0baa8c38c09fbe39d8af3dc1e49a95bc07bc5f6a039c83d860f9c1d21f300df585ebb63a4c5daf499fed2fe34cb56f8c5aab3d207be4ce18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
